name: Generate SBOM with AI Scanner

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout demo_flask_app
        uses: actions/checkout@v4
        with:
          path: demo_flask_app
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout sbom_ai_scanner
        uses: actions/checkout@v4
        with:
          repository: dsppun/sbom_ai_scanner
          path: sbom_ai_scanner

      - name: Install repomix
        run: npm install -g repomix
      
      - name: Create repomix output
        run: repomix demo_flask_app --output repomix-output.txt --style plain

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: pip install google-generativeai
      
      - name: Run SBOM analysis
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          cp repomix-output.txt sbom_ai_scanner/
          cd sbom_ai_scanner
          python sbom_scanner.py
          cp VERSION.md ../

      - name: Commit and push VERSION.md
        run: |
          cd demo_flask_app
          cp ../VERSION.md .
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add VERSION.md
          git commit -m "Update VERSION.md with SBOM analysis" || exit 0
          git push
      
      - name: Upload VERSION.md
        uses: actions/upload-artifact@v4
        with:
          name: sbom-report
          path: VERSION.md
